### ISSUE TITLE
Add unit of measurement localization

### ISSUE THREAD

**Issue by SiriosDev** [caiosweet/Home-Assistant-custom-components-INGV#25]
the sensor is great in English but in the other languages (currently it/pt) it is inconsistent, I wanted to open a PR but I didn't understand how to do it, I only found the translation files

**Comment by caiosweet** [comment]
That's right. There is no unit of measurement for the number of earthquakes. The only units of measurement are those listed [here](https://developers.home-assistant.io/docs/core/entity/sensor/). For this reason I chose to force a constant in English "quakes" as the unit of measurement. (another word that could be used would be "events")

**Comment by SiriosDev** [comment]
is it not possible to create a translation file for the unit of measurement? `if Italian use terremoti(or maybe scosse) if English use quakes etc. `

**Comment by caiosweet** [comment]
I have no idea, but I can suggest a much quicker way that solves your problem.
Use [customize](https://www.home-assistant.io/docs/configuration/customizing-devices/#unit_of_measurement).

Just add something similar (see the code below) to the yaml configuration file, then choose restart and quick restart and you will have the unit of measurement that is inserted in the entity customization (my entity ID is `sensor.ingv_earthquakes_casa_status`, obviously you will have to use yours if it is different 😄)

```
homeassistant:
  customize:
    # Add an entry for each entity that you want to overwrite.
    sensor.ingv_earthquakes_casa_status:
      unit_of_measurement: "scosse"
```
